name: Test
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Install then test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        browser: [ chrome, firefox, webkit ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install
        run: |
          yarn --immutable
          yarn playwright install ${{ matrix.browser }}
          yarn playwright install-deps ${{ matrix.browser }}

      - name: Run Test
        continue-on-error: true
        run: yarn test --profile ${{ matrix.browser }}

      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: test-report-${{ matrix.browser }}
          path: reports/*

  report:
    name: "Report"
    runs-on: ubuntu-22.04
    needs:
      - test
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v2
        with:
          path: reports

      - name: Move Test Report
        run: |
          mv reports/test-report-*/* reports

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install deps
        run: yarn --immutable

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: 'reports/*.xml'

      - name: Generate HTML Report
        if: always()
        run: yarn gen:report

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
